# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff167fe178eafcda4b0414d0dc9b3cc8a67945b047f176bb1c502e620a1d2046b1a5eb6027c793049b7c9be43618bb83edc06dc7456ce9e5ba37aaae6a488f4a

test:
  secret_key_base: bdac756ae068e2d4aaac570e6cc7599445c54b872f3971725f74f27a97319b8b16583c349a1be6af958bee264d1f987e8844cccf771c578d0ac88c2c5be1255a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
